title: Anthony O'Donnell
author: Anthony O'Donnell
email: anthony.odonnell@outlook.com
description: > 
  Software Testing Blog
show_excerpts: true 

sass:
  sass_dir: _sass
plainwhite:
  name: Anthony O'Donnell
  tagline: Software Tester
  date_format: "%d %b %Y"
  sitemap: true
  analytics_id: UA-76033218-5
  disqus_shortname: anthonyodonnell
  google_ads_client: ca-pub-8614161100865863

  social_links:
    youtube_channel: UCJyxFpItIyGet8p5928voEw
    github:  odonnell-anthony
    linkedIn: in/anthonyodonnell


# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed