title: Anthony O'Donnell
author: Anthony O'Donnell
email: anthony.odonnell@outlook.com
description: > # this means to ignore newlines until "show_exerpts:"
  Software Testing Blog
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Anthony O'Donnell
  tagline: Software Tester
  date_format: "%d %b %Y"
  sitemap: true # set to true to generate sitemap.xml content
  analytics_id: UA-76033218-5
  disqus_shortname: anthonyodonnell

  # generate social links in footer
  social_links:
    youtube_channel: UCJyxFpItIyGet8p5928voEw
    github:  odonnell-anthony
    linkedIn: in/anthonyodonnell
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed